image: composer:2.0
pipelines:
  branches:
    master:
    - step:
        script:
          - pipe: atlassian/ftp-deploy:0.3.6
            variables:
              USER: $FTP_USERNAME
              PASSWORD: $FTP_PASSWORD
              SERVER: ftp.codeartssolution.com